---
- name: Setting up db server
  hosts: dbservergrp
  become: yes  
  tasks:
    - debug:
        var: dbname
    - debug:
        msg: "value for dbuser is {{dbuser}}"
        
    - name: Install mysql in remote vm
      apt:
       name: mysql-server
       state: present
    - name: Start mysql-server
      service:
       name: mysql
       state: started
       enabled: yes
    - name: Install python3-PyMySQL on remote vm
      apt:
        name: python3-pymysql
        state: present
    - name: Create a new database with name 'devopsdb'
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{dbname}}"
        state: present


    - name: Create database user with name 'devops' with all database privileges
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'

